version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
