[project]
name = "redis-container"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
[project.scripts]
serve = "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
